### ISSUE TITLE
UX problem, same day number is still selected when changing month

### ISSUE THREAD

**Issue by alcalyn** [chrisdavies/tiny-date-picker#37]
### Reproduce it:

- I set a date in the datepicker, i.e the 15 May 2017
- I close the datepicker
- I reopen the datepicker (then the 15 is selected with `dp.current`, which is fine)
- I change the month by clicking on `<`, `>` or though the month selector, i.e April 2017

### Expected result:

I should not see any selected day until I click one of them

### Current result:

The 15 April 2017 is selected, then it looks like the date is set to April 15, but is not.

I think it should not be selected to don't forget to select a day and "validate" the date. By leaving it selected, it looks like the date is well changed when I change the month, and I close the datepicker without having changed the date.

**Comment by chrisdavies** [comment]
This is really a CSS issue. I agree with you, though. I modified the CSS defaults for the project (see the demo page).

But for the record, you can customize the way the current selection looks vs the currently selected date by adjusting these classes:

```css
.dp-day:hover,
.dp-month:hover,
.dp-year:hover,
.dp-current:focus,
.dp-current,
.dp-day:focus,
.dp-month:focus,
.dp-year:focus {
  outline: none;
  background: #75BCFC;
  color: white;
}

.dp-selected:hover,
.dp-selected:focus,
.dp-selected {
  background: #3B99FC;
  color: #FFF;
}
```
