### ISSUE TITLE
Datepicker is not working on top of Bootstrap Model.

### ISSUE THREAD

**Issue by 2rohith2** [chrisdavies/tiny-date-picker#66]
@chrisdavies Could you please look into this, I have a Bootstrap Model, in the model I have *DOB* to be selected by the user, but when I click input field the date picker is going behind the model.

Could you please give me some inputs to fix this.

**Comment by chrisdavies** [comment]
The Modal's z-index is higher than the date-picker's. So, you need to write a little CSS that either: bumps the date picker's z-index up a bit, or that drops the modal's z-index lower.

For the date picker, this should suffice:

```css
.dp-below,
.dp-modal {
    z-index: 100000; /* or some crazy high number*/
}
```

I avoid bootstrap, personally, so I don't know what their modal's z-index defaults to. But that should fix your problem, I think.
